import base64
from pathlib import Path


def get_pssh(raw: bytes) -> bytes:
    offset = raw.rfind(b"pssh")
    return raw[offset - 4 : offset - 4 + raw[offset - 1]]


def pssh_from_file_naive(file_path: Path) -> str:
    data = file_path.read_bytes()
    pssh = get_pssh(data)
    return base64.b64encode(pssh).decode()


# generated by chatgpt
def find_pssh_in_file(file_path: Path, chunk_size: int = 1024 * 1024) -> str | None:
    pattern = b"pssh"
    with file_path.open("rb") as f:
        prev = b""
        while True:
            chunk = f.read(chunk_size)
            if not chunk:
                break
            data = prev + chunk
            offset = data.rfind(pattern)
            if offset != -1:
                # Safety check: ensure enough bytes exist for box length field
                if offset >= 4 and offset + 1 < len(data):
                    box_len = data[offset - 4 + 3]
                    start = offset - 4
                    end = start + box_len
                    return base64.b64encode(data[start:end]).decode()
            # keep last few bytes in case pattern spans chunks
            prev = data[-8:]
    return None


def extract_pssh_from_m3u8(file_path: Path) -> str | None:
    index_content = file_path.read_text()
    marker = "base64,"
    pos = index_content.find(marker)
    if pos == -1:
        return None
    b64 = index_content[pos + len(marker) :].split('"')[0]
    return b64
